### ISSUE TITLE
Oddities in the log file

### ISSUE THREAD

**Issue by pkeberly** [mr-manuel/venus-os_dbus-serialbattery#126]
### Describe the problem

The driver worked yesterday on the bench.  Today I noticed some errors in the log file after a reboot.  I was editing config.ini end of day yesterday so it might be pilot error.

### Driver version of the currently installed driver

1.5.20241202

### Venus OS device type

Cerbo GX

### Venus OS version

V3.6~8

### BMS type

Jiabaida JDB BMS (LLT Power, Overkill Solar, Smart BMS)

### Cell count

8

### Battery count

1

### Connection type

Serial USB adapter to TTL

### Config file

```ini
[DEFAULT]

; If you want to add custom values/settings, then check the values/settings you want to change in "config.default.ini"
; and insert them below to persist future driver updates.

; --------- Set logging level ---------
; ERROR: Only errors are logged
; WARNING: Errors and warnings are logged
; INFO: Errors, warnings, and info messages are logged
; DEBUG: Errors, warnings, info, and debug messages are logged
LOGGING = INFO

; --------- Battery Current Limits ---------
MAX_BATTERY_CHARGE_CURRENT = 150.0
MAX_BATTERY_DISCHARGE_CURRENT = 200.0

; --------- Cell Voltages ---------
; Description:
;     Minimum and maximum cell voltages used for:
;         - Calculating the minimum and maximum battery voltage
;         - Triggering the SoC reset when SoC calculation is enabled
; Example:
;     8 cells * 3.52 V/cell = 28.16 V max charge voltage (default was 3.45 V)
;     8 cells * 2.90 V/cell = 23.20 V min discharge voltage
; Minimum voltage (can be seen as cut-off voltage)
MIN_CELL_VOLTAGE   = 2.900
; Maximum voltage (can be seen as absorption voltage)
MAX_CELL_VOLTAGE   = 3.520
; Float voltage (can be seen as resting voltage)
FLOAT_CELL_VOLTAGE = 3.375


; --------- SoC Calculation ---------
; +++ This section is independent and unrelated to the "SoC reset voltage" section above. +++
; This is used to calculate the SoC in the driver instead of using the SoC reported by the BMS.
; Description:
;     Calculate the SoC in the driver. Do not use the SoC reported by the BMS.
; SOC_CALCULATION:
;     True: Calculate SoC in the driver, do not use SoC reported from BMS.
;         - The SoC is calculated by integrating the current reported.
;         - The current reported can be corrected by the map
;           (SOC_CALC_CURRENT_REPORTED_BY_BMS, SOC_CALC_CURRENT_MEASURED_BY_USER).
;         - The SoC is set to 100% if the following conditions apply for at least SOC_RESET_TIME seconds:
;             * Highest cell voltage is higher or equal to MAX_CELL_VOLTAGE.
;             * Current is lower than SOC_RESET_CURRENT.
;         - The SoC is set to 0% if the following conditions apply for at least SOC_RESET_TIME seconds:
;             * Lowest cell voltage is lower or equal to MIN_CELL_VOLTAGE.
;             * Battery is discharging.
;         - The calculated SoC is stored in dbus to persist a driver restart.
;     False: Use SoC reported from BMS (none of the other parameters apply).
; More info: https://github.com/Louisvdw/dbus-serialbattery/pull/868
SOC_CALCULATION   = True
SOC_RESET_CURRENT = 7
SOC_RESET_TIME    = 60
SOC_CALC_CURRENT_REPORTED_BY_BMS  = -300, 300
SOC_CALC_CURRENT_MEASURED_BY_USER = -300, 300
; Example to set small currents to zero:
;     SOC_CALC_CURRENT_REPORTED_BY_BMS  = -300, -0.5, 0.5, 300
;     SOC_CALC_CURRENT_MEASURED_BY_USER = -300,    0,   0, 300



; --------- BMS Disconnect Behavior ---------
; Description:
;     Block charge and discharge when communication with the BMS is lost. If you are removing the
;     BMS intentionally, you must restart the driver/system to reset the block.
; False:
;     Charge and discharge are not blocked for 20 minutes if cell voltages are between
;     BLOCK_ON_DISCONNECT_VOLTAGE_MIN and BLOCK_ON_DISCONNECT_VOLTAGE_MAX. Otherwise, the driver blocks charge and discharge
;     after 60 seconds.
; True:
;     Charge and discharge are blocked immediately on BMS communication loss. They are unblocked when the connection is re-established
;     or the driver/system is restarted. This is the default behavior for Victron Energy devices.
BLOCK_ON_DISCONNECT = True
; Specify in minutes how long the driver should continue to charge and discharge after BMS communication is lost.
BLOCK_ON_DISCONNECT_TIMEOUT_MINUTES = 20
; Specify a voltage range where the last fetched values of the driver should be to avoid blocking charging and discharging.
; This is needed since during this time the driver has no information about the battery status.
; The range should be safe for the battery to operate without information for 20 minutes.
BLOCK_ON_DISCONNECT_VOLTAGE_MIN = 3.25
BLOCK_ON_DISCONNECT_VOLTAGE_MAX = 3.35



; --------- Charge Mode ---------
; Choose the mode for voltage/current limitations (True/False).
; False: Step mode (default) with limitations on hard boundary steps.
; True: Linear mode with smoother values.
;     For CCL and DCL, values between steps are calculated for smoother transitions.
;     For CVL, the max battery voltage is calculated dynamically to ensure the max cell voltage is not exceeded.
LINEAR_LIMITATION_ENABLE = True

; Specify in seconds how often the linear values should be recalculated.
LINEAR_RECALCULATION_EVERY = 60
; Specify the percentage change that triggers an immediate recalculation of linear values.
; Example:
;     33 means an immediate change when the value changes by more than 33%.
LINEAR_RECALCULATION_ON_PERC_CHANGE = 33



; --------- Charge Voltage Limitation (affecting CVL) ---------
; Description:
;     Limit the maximum charging voltage (MAX_CELL_VOLTAGE * cell count), switch from max voltage to float
;     voltage (FLOAT_CELL_VOLTAGE * cell count) and back.
;     False: Max charging voltage is always maintained.
;     True: Max charging voltage is reduced based on charge mode.
;         Linear mode: After max voltage is reached and cell voltage difference is smaller or equal to
;             CELL_VOLTAGE_DIFF_KEEP_MAX_VOLTAGE_UNTIL, it switches to float voltage after MAX_VOLTAGE_TIME_SEC
;             additional seconds.
;             After cell voltage difference is greater or equal to CELL_VOLTAGE_DIFF_TO_RESET_VOLTAGE_LIMIT
;             OR
;             SoC is below SOC_LEVEL_TO_RESET_VOLTAGE_LIMIT,
;             it switches back to max voltage.

; Example when set to True:
;     Linear mode:
;          The battery reaches a max voltage of 28.16 V and the max cell difference is 0.010 V, then switch to float
;          voltage of 27.00 V after 900 additional seconds to reduce stress on the batteries. Max voltage of
;          28.16 V is allowed again if the max cell difference exceeds 0.080 V or SoC drops below 80%.
; Enable charge voltage control management (True/False).
CVCM_ENABLE = True

; -- CVL reset based on cell voltage difference (linear mode)
; Specify the cell voltage difference where CVL limit is maintained until the difference is equal or lower.
CELL_VOLTAGE_DIFF_KEEP_MAX_VOLTAGE_UNTIL        = 0.010
; Specify the cell voltage difference where MAX_VOLTAGE_TIME_SEC restarts if the difference is larger.
CELL_VOLTAGE_DIFF_KEEP_MAX_VOLTAGE_TIME_RESTART = 0.013
; Specify the cell voltage difference where CVL limit is reset to max voltage if the value exceeds this threshold.
; Cells are considered imbalanced if the cell difference exceeds 5% of the nominal cell voltage.
; Example: 3.2 V * 5 / 100 = 0.160 V
CELL_VOLTAGE_DIFF_TO_RESET_VOLTAGE_LIMIT = 0.080

; -- CVL reset based on SoC (step mode & linear mode)
; Specify how long the max voltage should be maintained.
;     Linear mode: If cells are balanced, maintain max voltage for an additional MAX_VOLTAGE_TIME_SEC seconds.
MAX_VOLTAGE_TIME_SEC = 900
; Specify the SoC level where CVL limit is reset to max voltage.
;     Linear mode: If cells are unbalanced or if SoC drops below this level.
SOC_LEVEL_TO_RESET_VOLTAGE_LIMIT = 80



; --------- Cell Voltage Current Limitation (affecting CCL/DCL) ---------
; Description:
;     The maximum charge/discharge current will be increased or decreased depending on the minimum and maximum cell voltages.
; Example:
;     8 cells * 3.62 V/cell = 28.96 V max charge voltage
;     8 cells * 2.70 V/cell = 21.60 V min discharge voltage
;     In reality, not all cells reach the same voltage at the same time. The (dis)charge current
;     will be (in-/)decreased if even one single battery cell reaches the limits.

; Enable charge current control management based on cell voltage (True/False).
CCCM_CV_ENABLE = True
; Enable discharge current control management based on cell voltage (True/False).
DCCM_CV_ENABLE = True

; Set steps to reduce battery current. (PWK rescaled CELL_VOLTAGES_WHILE_CHARGING up 70 mV)
; The current will be changed linearly between these steps if LINEAR_LIMITATION_ENABLE is set to True.
CELL_VOLTAGES_WHILE_CHARGING      = 3.62, 3.57, 3.52, 3.37
MAX_CHARGE_CURRENT_CV_FRACTION    =    0, 0.05,  0.5,    1 

CELL_VOLTAGES_WHILE_DISCHARGING   = 2.70, 2.80, 2.90, 3.10
MAX_DISCHARGE_CURRENT_CV_FRACTION =    0,  0.1,  0.5,    1


; --------- Temperature Limitation (affecting CCL/DCL) ---------
; Description:
;     The maximum charge/discharge current will be increased or decreased depending on temperatures.
;     NOTE: The temperatures are in Â°Celsius. Temperature sensors 1 to 4 are used for the calculation.
; Example:
;     The temperature limit will be monitored to control the currents. If there are two temperature sensors,
;     the worst case will be calculated, and the more secure lower current will be set.
; Enable charge current control management based on temperature (True/False).
CCCM_T_ENABLE = True
; Enable discharge current control management based on temperature (True/False).
DCCM_T_ENABLE = True

; Set steps to reduce battery current.
; The current will be changed linearly between these steps if LINEAR_LIMITATION_ENABLE is set to True.
TEMPERATURES_WHILE_CHARGING      =    0,    2,    5,   10,   15,   20,   35,   40,   55
MAX_CHARGE_CURRENT_T_FRACTION    = 0.00, 0.10, 0.20, 0.40, 0.80, 1.00, 1.00, 0.40, 0.00

TEMPERATURES_WHILE_DISCHARGING   =  -20,    0,    5,   10,   15,   45,   55
MAX_DISCHARGE_CURRENT_T_FRACTION = 0.00, 0.20, 0.30, 0.40, 1.00, 1.00, 0.00


; --------- CCL/DCL Recovery Threshold ---------
; Description:
;     This threshold applies if any of the following limitations are enabled:
;         - Cell Voltage Current Limitation (CCCM_CV_ENABLE, DCCM_CV_ENABLE)
;         - Temperature Limitation (CCCM_T_ENABLE, DCCM_T_ENABLE)
;         - SoC Limitation (CCCM_SOC_ENABLE, DCCM_SOC_ENABLE)
;     Once the current reaches 0, it will only increase again if it exceeds this threshold.
;     The threshold is a percentage of the maximum charge/discharge current.
;     This prevents rapid switching (flapping) between allowing and blocking charge/discharge, which can cause system instability and excessive notifications.
; Example:
;     If the maximum charge current is 50 A and the threshold is set to 0.02 (2%), the current must exceed 1A (50A * 0.02) before charging resumes.
;     If the maximum discharge current is 60 A and the threshold is set to 0.02 (2%), the current must exceed 1.2A (60A * 0.02) before discharging resumes.
CHARGE_CURRENT_RECOVERY_THRESHOLD_PERCENT = 0.015
DISCHARGE_CURRENT_RECOVERY_THRESHOLD_PERCENT = 0.015


; --------- Additional settings ---------
; Specify one or more BMS types (separated by a comma) to load, or leave empty to try to load all available.
;
BMS_TYPE = LltJbd

; Publish the config settings to the dbus path "/Info/Config/".
PUBLISH_CONFIG_VALUES = True

; Select the format of cell data presented on dbus.
; 0 Do not publish all the cells (only the min/max cell data as used by the default GX)
; 1 Format: /Voltages/Cell (also available for display on Remote Console)
; 2 Format: /Cell/#/Volts
; 3 Both formats 1 and 2
BATTERY_CELL_DATA_FORMAT = 0


; Battery temperature
; Specify how the battery temperature is assembled.
; 0 Get mean of temperature sensor 1 to sensor 4
; 1 Get only temperature from temperature sensor 1
; 2 Get only temperature from temperature sensor 2
; 3 Get only temperature from temperature sensor 3
; 4 Get only temperature from temperature sensor 4
TEMP_BATTERY = 0

; Temperature sensor 1 name
TEMP_1_NAME = Temp 1

; Temperature sensor 2 name
TEMP_2_NAME = Temp 2

; Temperature sensor 3 name
TEMP_3_NAME = Temp 3

; Temperature sensor 4 name
TEMP_4_NAME = Temp 4

; Show additional info in GUI -> Serialbattery -> Parameters.
; This will show additional information to better understand how the driver works
; and what values are currently set which are not shown elsewhere in the GUI.
; You have to scroll down to see the additional information.
GUI_PARAMETERS_SHOW_ADDITIONAL_INFO = True

; Telemetry settings
; To help us improve the driver, we are collecting telemetry data. This data is anonymous and
; will only be used to improve the driver. The data is sent once every week.
; You can disable this feature by setting this value to False.
; Some data we collect: Venus OS version, driver version, driver runtime, battery type, battery count.
TELEMETRY = True

; -- LltJbd settings
; SoC low levels
; Note:
;     SOC_LOW_WARNING can be used to calculate the Time-To-Go, even if you are not using an LltJbd BMS.
SOC_LOW_WARNING = 20
SOC_LOW_ALARM   = 10
```

### Relevant log output

```shell
@40000000675c68d32f0116b4 INFO:SerialBattery:-- Testing BMS: 1 of 3 rounds
@40000000675c68d32f11eb4c INFO:SerialBattery:Testing LltJbd at address "\x00"
@40000000675c68d5144dbf0c INFO:SerialBattery:-- Connection established to LltJbd
@40000000675c68d91eebf654 INFO:SerialBattery:Reconnected to previously identified battery with DeviceInstance: 3
@40000000675c68d92184b234 ERROR:SerialBattery:Failed to remove setting: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
@40000000675c68d92184e4fc   File "/usr/lib/python3.8/site-packages/dbus/service.py", line 658, in _message_cb
@40000000675c68d92184f49c     (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
@40000000675c68d92185043c   File "/usr/lib/python3.8/site-packages/dbus/service.py", line 248, in _method_lookup
@40000000675c68d921850ff4     raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
@40000000675c68d921879864 dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: remove_settingss is not a valid method of interface com.victronenergy.Settings
@40000000675c68d92187b7a4 
@40000000675c68d9220af54c INFO:SerialBattery:Remove /Settings/Devices/serialbattery_ttyUSB0 from dbus. Old entry. Delete result: None
@40000000675c68d9247a62f4 ERROR:SerialBattery:Failed to remove setting: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
@40000000675c68d9247a8dec   File "/usr/lib/python3.8/site-packages/dbus/service.py", line 658, in _message_cb
@40000000675c68d9247a9d8c     (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
@40000000675c68d9247aad2c   File "/usr/lib/python3.8/site-packages/dbus/service.py", line 248, in _method_lookup
@40000000675c68d9247ab8e4     raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
@40000000675c68d9247c62ac dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: remove_settingss is not a valid method of interface com.victronenergy.Settings
@40000000675c68d9247c7e04 
@40000000675c68d924f4710c INFO:SerialBattery:Remove /Settings/Devices/serialbattery_ttyUSB1 from dbus. Old entry. Delete result: None
@40000000675c68db008775bc INFO:SerialBattery:Use DeviceInstance: 3
@40000000675c68db00ab034c INFO:SerialBattery:Use dbus ServiceName: com.victronenergy.battery.ttyUSB0
@40000000675c68db0a681dac INFO:SerialBattery:Polling interval: 1.000 s
@40000000675c68db0b373934 INFO:SerialBattery:Battery LLT/JBD connected to dbus from /dev/ttyUSB0
@40000000675c68db0b4ef754 INFO:SerialBattery:========== Settings ==========
@40000000675c68db0c5da064 INFO:SerialBattery:> Connection voltage: 25.76 V | Current: 0.0 A | SoC: 14% | SoC calc: 15%
@40000000675c68db0c6a69d4 INFO:SerialBattery:> Cell count: 8 | Cells populated: 8
@40000000675c68db0c768764 INFO:SerialBattery:> LINEAR LIMITATION ENABLE: True
@40000000675c68db0d66ea74 INFO:SerialBattery:> MIN CELL VOLTAGE: 2.900 V | MAX CELL VOLTAGE: 3.520 V| FLOAT CELL VOLTAGE: 3.375 V
@40000000675c68db0d75d2dc INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 150.0 A | MAX BATTERY DISCHARGE CURRENT: 200.0 A
@40000000675c68db0d83ec3c INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 300.0 A | MAX BATTERY DISCHARGE CURRENT: 300.0 A (read from BMS)
@40000000675c68db0d90dcbc INFO:SerialBattery:> CVCM:     True
@40000000675c68db0d9d67ac INFO:SerialBattery:> CCCM CV:  True  | DCCM CV:  True
@40000000675c68db0daf8464 INFO:SerialBattery:> CCCM T:   True  | DCCM T:   True
@40000000675c68db0db8a454 INFO:SerialBattery:> CCCM SOC: False | DCCM SOC: False
@40000000675c68db0dc542cc INFO:SerialBattery:> CHARGE FET: True | DISCHARGE FET: True | BALANCE FET: True
@40000000675c68db0dd4bfa4 INFO:SerialBattery:Serial Number/Unique Identifier: 39_304.0Ah
@40000000675c68dc11674ca4 ERROR:SerialBattery:>>> ERROR: Invalid response packet. Expected begin packet character 0xDD
@40000000675c68dc1179bb64 WARNING:SerialBattery:>>> WARN: BMS rejected request. Status 10
@40000000675c68dc11946b6c INFO:SerialBattery:cell_voltages_good: False - min: 3.219 > 3.25 - max: 3.223 < 3.35
@40000000675c68f21c4f565c ERROR:SerialBattery:>>> ERROR: Invalid response packet. Expected begin packet character 0xDD
@40000000675c68f21c5f159c WARNING:SerialBattery:>>> WARN: BMS rejected request. Status 192
@40000000675c68f21d094bd4 INFO:SerialBattery:cell_voltages_good: False - min: 3.219 > 3.25 - max: 3.223 < 3.35
@40000000675c68f528e3088c ERROR:SerialBattery:>>> ERROR: BMS send insufficient data. Received 50 expected 45
@40000000675c68f528f4fe34 INFO:SerialBattery:cell_voltages_good: False - min: 3.219 > 3.25 - max: 3.223 < 3.35
@40000000675c68f7206bd7c4 ERROR:SerialBattery:>>> ERROR: Invalid response packet. Expected begin packet character 0xDD
@40000000675c68f7207a2004 ERROR:SerialBattery:>>> ERROR: BMS send insufficient data. Received 25 expected 7
@40000000675c68f7208fbb44 INFO:SerialBattery:cell_voltages_good: False - min: 3.219 > 3.25 - max: 3.223 < 3.35
@40000000675c69082b1c2fac ERROR:SerialBattery:>>> ERROR: No reply - returning [len:22/22]
@40000000675c69082b65cb6c ERROR:SerialBattery:>>> ERROR: Battery does not respond, init/reset values <<<
@40000000675c69082c38bf54 Traceback (most recent call last):
@40000000675c69082c38e664   File "/opt/victronenergy/dbus-serialbattery/dbushelper.py", line 776, in publish_battery
@40000000675c69082c38f604     self.battery.manage_charge_voltage()
@40000000675c69082c38fdd4   File "/opt/victronenergy/dbus-serialbattery/battery.py", line 395, in manage_charge_voltage
@40000000675c69082c390d74     self.soc_calculation()
@40000000675c69082c391544   File "/opt/victronenergy/dbus-serialbattery/battery.py", line 465, in soc_calculation
@40000000675c69082c3ac6dc     self.soc_calc_capacity_remain + self.current_corrected * (current_time - self.soc_calc_capacity_remain_lasttime) / 3600
@40000000675c69082c3ade4c TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
@40000000675c693b2b2d90e4 INFO:SerialBattery:
@40000000675c693b2b3b1da4 INFO:SerialBattery:Starting dbus-serialbattery
@40000000675c693b2ba71e14 INFO:SerialBattery:Venus OS v3.60~8 running on Cerbo GX
```

**Comment by mr-manuel** [comment]
This was a bug and I fixed it. Please reinstall the latest stable version.

**Comment by pkeberly** [comment]
That was your latest version.  I tried your latest beta this morning and some oddities still exist.
I have not yet tried to revert to earlier versions of Venus.  If you feel the driver is safe to continue bench testing with, we can ignore it for now.   It appears to be a typo in a method name?? "remove_settings**s**"

<code>
2024-12-14 15:50:22.376229500 INFO:SerialBattery:
2024-12-14 15:50:22.376946500 INFO:SerialBattery:Starting dbus-serialbattery
2024-12-14 15:50:22.379073500 INFO:SerialBattery:Venus OS v3.60~8
2024-12-14 15:50:22.379695500 INFO:SerialBattery:dbus-serialbattery v1.5.20241119beta
2024-12-14 15:50:38.386993500 INFO:SerialBattery:-- Testing BMS: 1 of 3 rounds
2024-12-14 15:50:38.388146500 INFO:SerialBattery:Testing LltJbd at address "\x00"
2024-12-14 15:50:39.785224500 INFO:SerialBattery:-- Connection established to LltJbd
2024-12-14 15:50:42.807118500 INFO:SerialBattery:Reconnected to previously identified battery with DeviceInstance: 3
2024-12-14 15:50:42.840121500 ERROR:SerialBattery:Failed to remove setting: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
2024-12-14 15:50:42.840131500   File "/usr/lib/python3.8/site-packages/dbus/service.py", line 658, in _message_cb
2024-12-14 15:50:42.840135500     (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
2024-12-14 15:50:42.840139500   File "/usr/lib/python3.8/site-packages/dbus/service.py", line 248, in _method_lookup
2024-12-14 15:50:42.840143500     raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
2024-12-14 15:50:42.840245500 dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: remove_settingss is not a valid method of interface com.victronenergy.Settings
2024-12-14 15:50:42.840252500 
2024-12-14 15:50:42.850818500 INFO:SerialBattery:Remove /Settings/Devices/serialbattery_ttyUSB0 from dbus. Old entry. Delete result: None
2024-12-14 15:50:42.883049500 ERROR:SerialBattery:Failed to remove setting: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
2024-12-14 15:50:42.883062500   File "/usr/lib/python3.8/site-packages/dbus/service.py", line 658, in _message_cb
2024-12-14 15:50:42.883066500     (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
2024-12-14 15:50:42.883070500   File "/usr/lib/python3.8/site-packages/dbus/service.py", line 248, in _method_lookup
2024-12-14 15:50:42.883073500     raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
2024-12-14 15:50:42.883188500 dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: remove_settingss is not a valid method of interface com.victronenergy.Settings
2024-12-14 15:50:42.883196500 
2024-12-14 15:50:42.893952500 INFO:SerialBattery:Remove /Settings/Devices/serialbattery_ttyUSB1 from dbus. Old entry. Delete result: None
2024-12-14 15:50:43.274110500 INFO:SerialBattery:Use DeviceInstance: 3
2024-12-14 15:50:43.276021500 INFO:SerialBattery:Use dbus ServiceName: com.victronenergy.battery.ttyUSB0
2024-12-14 15:50:43.343386500 INFO:SerialBattery:Polling interval: 1.000 s
2024-12-14 15:50:43.343395500 INFO:SerialBattery:Battery LLT/JBD connected to dbus from /dev/ttyUSB0
2024-12-14 15:50:43.343535500 INFO:SerialBattery:========== Settings ==========
2024-12-14 15:50:43.344647500 INFO:SerialBattery:> Connection voltage: 25.85 V | Current: 0.0 A | SoC: 14% | SoC calc: 15%
2024-12-14 15:50:43.345572500 INFO:SerialBattery:> Cell count: 8 | Cells populated: 8
2024-12-14 15:50:43.346489500 INFO:SerialBattery:> LINEAR LIMITATION ENABLE: True
2024-12-14 15:50:43.347516500 INFO:SerialBattery:> MIN CELL VOLTAGE: 2.900 V | MAX CELL VOLTAGE: 3.520 V| FLOAT CELL VOLTAGE: 3.375 V
2024-12-14 15:50:43.351672500 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 150.0 A | MAX BATTERY DISCHARGE CURRENT: 200.0 A
2024-12-14 15:50:43.351684500 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 300.0 A | MAX BATTERY DISCHARGE CURRENT: 300.0 A (read from BMS)
2024-12-14 15:50:43.351689500 INFO:SerialBattery:> CVCM:     True
2024-12-14 15:50:43.351692500 INFO:SerialBattery:> CCCM CV:  True  | DCCM CV:  True
2024-12-14 15:50:43.351904500 INFO:SerialBattery:> CCCM T:   True  | DCCM T:   True
2024-12-14 15:50:43.353058500 INFO:SerialBattery:> CCCM SOC: False | DCCM SOC: False
2024-12-14 15:50:43.355521500 INFO:SerialBattery:> CHARGE FET: True | DISCHARGE FET: True | BALANCE FET: True
2024-12-14 15:50:43.360661500 INFO:SerialBattery:Serial Number/Unique Identifier: 39_304.0Ah

</code>

**Comment by mr-manuel** [comment]
> That was your latest version.

Yes, but I rebuild it with the fix.

Yes it‘s a typo. Should be `RemoveSettings`. As written above, I fixed the `v1.5.20241202` build. If you do a online reinstall, then it‘s fixed using the tar file.

Else the nightly works well.

**Comment by mr-manuel** [comment]
I released a new version [`v1.5.20241215`](https://github.com/mr-manuel/venus-os_dbus-serialbattery/releases/tag/v1.5.20241215) with the fix now.

The SoC is very inaccurate, therefore the `CCL` and `DCL` by SoC are disabled by default. 

https://github.com/mr-manuel/venus-os_dbus-serialbattery/blob/416f9e5fcac8049ae37c64209dc653044b396e4e/dbus-serialbattery/config.default.ini#L342-L353

Check the cell voltages instead of the SoC, which is enabled by default:

https://github.com/mr-manuel/venus-os_dbus-serialbattery/blob/416f9e5fcac8049ae37c64209dc653044b396e4e/dbus-serialbattery/config.default.ini#L301-L312

`CCCM_*_ENABLE` and `DCCM_*_ENABLE` are the only options that limit `CCL` and `DCL` in a soft way, without the BMS has to interrupt in the hard way by turning off charging/discharging.

https://github.com/mr-manuel/venus-os_dbus-serialbattery/blob/416f9e5fcac8049ae37c64209dc653044b396e4e/dbus-serialbattery/config.default.ini#L18-L24

**Comment by pkeberly** [comment]
I tried the latest beta & latest stable this morning.  Both produce an error, it looks like something is missing. What did I do wrong? 

ERROR: overlay-fs app not found. Please install it manually.




On Sunday, December 15, 2024 at 04:32:10 AM EST, Manuel ***@***.***> wrote: 







I released a new version v1.5.20241215 with the fix now.

The SoC is very inaccurate, therefore the CCL and DCL by SoC are disabled by default.

https://github.com/mr-manuel/venus-os_dbus-serialbattery/blob/416f9e5fcac8049ae37c64209dc653044b396e4e/dbus-serialbattery/config.default.ini#L342-L353

Check the cell voltages instead of the SoC, which is enabled by default:

https://github.com/mr-manuel/venus-os_dbus-serialbattery/blob/416f9e5fcac8049ae37c64209dc653044b396e4e/dbus-serialbattery/config.default.ini#L301-L312

CCCM_*_ENABLE and DCCM_*_ENABLE are the only options that limit CCL and DCL in a soft way, without the BMS has to interrupt in the hard way by turning off charging/discharging.

https://github.com/mr-manuel/venus-os_dbus-serialbattery/blob/416f9e5fcac8049ae37c64209dc653044b396e4e/dbus-serialbattery/config.default.ini#L18-L24

**Comment by mr-manuel** [comment]
Just stick with `v2.x.x`, if you already installed it once.

**Comment by pkeberly** [comment]
My apologizes but I don't see v2.x.x, and haven't installed that far yet.  I did select select the latest stable version and I still get the error. I even went back to a stable version of Venus to rule that out.

I have a second Cerbo-S GX that I tried to install the latest on, and it also gets "overlay-fs app not found" error.
I'm not sure what that error means or where to begin looking for problems.  

SSH install using Putty/Win11 with the command copied from the instructions.  This worked so well before, it seems to have went bad when the code moved from etc to apps?

Putty output from the Cerbo-S, 1202 driver was installed but never had the USB device plugged in.  

** Currently installed version: v1.5.20241202 **   

1) stable release "v1.5.20241215" (stable, most up to date)
2) beta build "v1.5.20241119beta" (no errors after 72 h runtime, long time testing needed)
3) nightly build "v2.0.20241211dev" (newest features and fixes, bugs possible)
4) specific branch (specific feature testing)
5) specific version
6) local tar file
7) quit

Select which version you want to install from m-rmanuel's repo and enter the corresponding number: 1
> Selected: stable release "v1.5.20241215" (stable, most up to date)

Config.ini backed up to /data/etc/dbus-serialbattery_config.ini.backup
Config.ini restored to /data/apps/dbus-serialbattery/config.ini
ERROR: overlay-fs app not found. Please install it manually.
***@***.***:~#

It appears the serial starter isn't happy about something.  I found this entry several places in the serial starter log file
ERROR: no service template for dbus-serialbattery

Thanks, 
Paul




On Monday, December 16, 2024 at 10:05:33 AM EST, Manuel ***@***.***> wrote: 




Just stick with v2.x.x, if you already installed it once.

**Comment by marcelrv** [comment]
Seeing the same here... trying to upgrade from earlier version.
note: running latest 3.6~beta

**Comment by pkeberly** [comment]
Thanks marcelrv, I suspected it might have been pilot error on my end.

I tried a few combinations tonight to see what would work.
v1.5.20241215driver with 3.6 beta 
v1.4.20240928 driver with 3.6 beta
v1.5.20241215 driver with 3.52 production
factory reset Cerbo, v1.4.20240928 driver with 3.6 beta
factory reset Cerbo, v1.4.20240928 driver with 3.52 production
reflashed the Cerbo image to 3.50 with v1.4.20240928 driver

All combinations ended with: ERROR: overlay-fs app not found . Please install it manually.
I see the current install of v1.4.20240928 is located in **data/apps** NOT **data/etc** as it was previously.   It looks like the v2 path changes have made it into earlier versions too :(

**Comment by mr-manuel** [comment]
The error was fixed.

**Comment by marcelrv** [comment]
Thx! Indeed, fixed for me with latest update.
